#!/usr/bin/env python
# coding: utf-8

# # Module 1

# #### In this assignment, you will work with ufo sightings data.
# - The data includes various data points about individual ufo sightings
# - Data File(s): ufo-sightings.csv

# In[11]:


###########################################################
### EXECUTE THIS CELL BEFORE YOU TO TEST YOUR SOLUTIONS ###
###########################################################

import imp, os, sys
sol = imp.load_compiled("solutions", "./solutions.py")
sol.get_solutions("ufo-sightings.csv")
from nose.tools import assert_equal


# In[12]:


'''
1. Import the csv module. Load and read the UFO sightings data set, from the ufo-sightings.csv file, 
into a DictReader inside a with statement.  Assume the data file is in the same directory as the code. 

Print the field names of the data set. Iterate over the reader to put the data into a list name "ufosightings".

'''

import csv
filepath = "ufo-sightings.csv"
ufosightings = [] 

# your code here
with open('ufo-sightings.csv', 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    
    for row in reader:
        ufosightings.append(row)


# In[13]:


##########################
### TEST YOUR SOLUTION ###
##########################

assert_equal(ufosightings, sol.ufosightings)
print("Success!")


# In[14]:


'''
2. How many sightings were there in total?  Put the count in "ufosightings_count" and print the result.
'''
# your code here
with open('ufo-sightings.csv', 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    
    ufosightings_count = 0
    for row in reader:
        ufosightings_count += 1
    print(ufosightings_count)


# In[5]:


##########################
### TEST YOUR SOLUTION ###
##########################

assert_equal(ufosightings_count, sol.ufosightings_count)
print("Success!")


# In[15]:


'''
3. How many sightings were there in the US?  Put the US sightings in "sightings_us" and print.

Hint: Check for ufo sightings where the country is 'us'.

'''

# your code here
with open('ufo-sightings.csv', 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    
    sightings_us = 0
    sightings_us = [row for row in reader if row["country"] == "us"]
    print(sightings_us)


# In[7]:


##########################
### TEST YOUR SOLUTION ###
##########################

assert_equal(sightings_us,  sol.sightings_us)
print("Success!")


# In[16]:


'''
4. Let's find the "fireball" sighting(s) that lasted more than ten seconds in US. 
Print the the datetime and state of each.  Put the data in "fball" and print the result.

Note: Consider only the US sightings stored in "sightings_us".

- Cast the duration in seconds to a float (decimal). 
- Check if duration is greater than 10. 
- Check if the shape is "fireball".

'''

#First, define a Python function that checks if a given duration (seconds) is "valid"
def is_valid_duration(duration_as_string):
# your code here
    
    try:
        duration = float(duration_as_string)
        if duration > 10:
            return True
    except ValueError:
        return False
            

with open('ufo-sightings.csv', 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    
    fball = []
    ten_second = [row for row in sightings_us if(is_valid_duration(row["duration (seconds)"]))]
    fball = [row for row in ten_second if(row["shape"] =="fireball")]
    print(fball)


# In[9]:


##########################
### TEST YOUR SOLUTION ###
##########################

assert_equal(fball, sol.fball)
print("Success!")


# In[17]:


'''
5. Sort the above list by duration. What was the datetime and duration of the longest sighting?  
Put the sorted list in "fballsorted" and print the result.

- Cast the duration in seconds to a float (decimal). 
- Sort in reverse order.

'''

# your code here
fballsorted = []
fballsorted = sorted(fball, key = lambda x: float(x["duration (seconds)"]), reverse = True)
for row in fballsorted:


  print((row['datetime'], row['duration (seconds)']))


# In[11]:


##########################
### TEST YOUR SOLUTION ###
##########################

assert_equal(fballsorted, sol.fballsorted)
print("Success!")


# In[18]:


'''
6. What state had the longest lasting "fireball"?   Put the state in "state" and print the result.

- Check if the shape is "fireball".
- Cast the duration in seconds to a float (decimal).
- Get the record with the largest (max) duration in seconds.
- Get the state for the record.

'''

# your code here
long_fball = max(fballsorted, key = lambda x: float(x["duration (seconds)"]))
state = (long_fball["state"])


# In[13]:


##########################
### TEST YOUR SOLUTION ###
##########################

assert_equal(state, sol.state)
print("Success!")


# In[19]:


'''
7. Let's assume that any sighting (of any shape) of 0 seconds is insignificant. 
Write code to filter out these extraneous records and get the shortest sighting overall now.  
Put the minimum duration in "min_duration" and print the result.  
Use ufosightings
Note: Consider all sightings stored in "ufosightings".

'''

# your code here
def is_valid_duration_two(duration_as_string):
    
    try:
        duration = float(duration_as_string)
        if duration > 0:
            return True
    except ValueError:
        return False

filter_sightings = [row for row in ufosightings if(is_valid_duration_two(row["duration (seconds)"]))]


min_sighting = min(filter_sightings, key = lambda x: float(x["duration (seconds)"]))
min_duration = float(min_sighting["duration (seconds)"])


# In[15]:


##########################
### TEST YOUR SOLUTION ###
##########################

assert_equal(min_duration, sol.min_duration)
print("Success!")


# In[28]:


'''
8. What are the top 3 shapes sighted, and how many sightings were there for each? 

Note: Consider all sightings stored in "ufosightings".

- Create a new list "sightings_shapes" containing values from the "shape" column in ufosightings.  
- Create a new dictionary "count" with values of that column as keys and the counts as values.
- Get a list of the dictionary keys and values using the items() method.  This will return a list of key:value pairs.
Sort the list of key:value pairs in reverse order, from greatest (most sightings) to least.

Get the top 3 and store in "top3shapes".  Print the result.

'''

#Create a new list containing values from the "shape" column in ufosightings.
# your code here

with open(filepath, 'r') as csvfile:  # open with a with statement

    reader = csv.DictReader(csvfile)  # load and read into a DictReader

    ufosightings = []

    for row in reader:
        ufosightings.append(row)

    
    sightings_shapes = []
    for row in ufosightings:
        if not row['shape'] in sightings_shapes:
            sightings_shapes.append(row['shape'])

    
    count = {}
    
    for row in ufosightings:
        
        if row['shape'] in count:
            count[row['shape']] = count[row['shape']] + 1
        else:
            
            count[row['shape']] = 1

    
    shape_count = count.items()
    
    shape_count = sorted(shape_count, key=lambda r: r[1])
    shape_count.reverse()

#count = {}
 #   for i in sightings_shapes:
  #  count[i] = count.get(i, 0) + 1    
   # print(count)
    

#Get a list of the dictionary keys and values (use the items() method) and sort them in reverse order, from greatest (most sightings) to least.
#Get and print the top 3.
# your code here
top3shapes = (sorted(count.items(), key=lambda kv: (kv[1], kv[0]   ), reverse = True)[0:3]) 
print(top3shapes)


# In[29]:


##########################
### TEST YOUR SOLUTION ###
##########################

assert_equal(sightings_shapes, sol.sightings_shapes)
print("Success!")


# In[30]:


##########################
### TEST YOUR SOLUTION ###
##########################

assert_equal(count, sol.count)
print("Success!")


# In[20]:


##########################
### TEST YOUR SOLUTION ###
##########################

assert_equal(top3shapes, sol.top3shapes)
print("Success!")

